# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1108, 374)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 391, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 381, 301))
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setAutoScroll(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(False)
        self.tableView.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.tab, "")
        self.solveInStrategies = QtWidgets.QPushButton(self.centralwidget)
        self.solveInStrategies.setGeometry(QtCore.QRect(410, 10, 251, 23))
        self.solveInStrategies.setObjectName("solveInStrategies")
        self.log = QtWidgets.QTextEdit(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(680, 10, 421, 311))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.log.setFont(font)
        self.log.setObjectName("log")
        self.reduceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.reduceBtn.setGeometry(QtCore.QRect(410, 40, 251, 23))
        self.reduceBtn.setObjectName("reduceBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1108, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.loadMenuItem = QtWidgets.QAction(MainWindow)
        self.loadMenuItem.setObjectName("loadMenuItem")
        self.menu.addAction(self.loadMenuItem)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Матричные игры"))
        self.solveInStrategies.setText(_translate("MainWindow", "Решить в чистых или смешанных стратегиях"))
        self.reduceBtn.setText(_translate("MainWindow", "Выполнить редукцию матрицы"))
        self.menu.setTitle(_translate("MainWindow", "Файл..."))
        self.loadMenuItem.setText(_translate("MainWindow", "Загрузить"))
